"""empty message

Revision ID: 795aa4f9d5d3
Revises: 6852c9d01837
Create Date: 2022-09-20 23:23:46.938265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '795aa4f9d5d3'
down_revision = '6852c9d01837'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('join_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'join_time')
    # ### end Alembic commands ###
